### ISSUE TITLE
support a file suffix for automatically enabling mode

### ISSUE THREAD

**Issue by aspiers** [punchagan/org2blog#140]
It's tedious to have to manually enable the minor mode via `M-x org2blog/wp-mode` each time  a blog post file is loaded.  Better would be to support a standard filename suffix such as `.o2b` and then automatically enable the minor mode, e.g.

```
(add-to-list 'auto-mode-alist ("\\.o2b$" . org-mode))
(add-hook 'org-mode-hook
          (lambda ()
            (and (buffer-file-name)
                 (string-match "\\.o2b$" (buffer-file-name))
                 (org2blog/wp-mode))))
```

**Comment by grettke** [comment]
- Desire: Automatically enable o2b minor mode after loading an o2b page or post
- Possible Approaches
  - file suffix
    - org2blog (o2b) files are just plain old Org-Mode files. They already
      have an extension ~.org~ so it would violate the principle of least
      astonishment to a new extension for blog pages and posts. So I don't
      like this approach.
  - magic-mode-alist or hook to check for `#+POSTID`
    - `#+POST_ID` doesn't show up until you post the file. So that wouldn't
      work. 
      - magic-mode-alist doesn't work for the same reason
  - file-variables and `eval` and new post template
    - Works just fine. Whenever I use `eval` as a file local variable it is
      because I don't want to learn enough about how the mode works. But it
      it ought to be avoided if possible.
  - file header `#+org2blog`
    - Org-Mode already contains the functions to access properties
    - We can add the check to the org-mode-hook
    - This is the best approach

This thread has been quiet for a while but it still a good one.

**Comment by grettke** [comment]
I just closed this [here](https://github.com/punchagan/org2blog/commit/c857ce755f4bc750bf88bb17e6ba8f2bd511c62d)

The docs and the code are updated: just include `#+ORG2BLOG` in the file and the mode will auto load.
