### ISSUE TITLE
URL/HTTP Error: 200 using blog at wordpress.com

### ISSUE THREAD

**Issue by shelper** [punchagan/org2blog#164]
here is my settings for org2blog

(setq org2blog/wp-blog-alist
      '(("wordpress"
         :url "http://username.wordpress.com/xmlrpc.php"
         :username "username"
         :password "password"
         :default-title ""
         ;; :track-posts nil
         :default-categories ("software")
         :tags-as-categories t)))

and here is my error message

Debugger entered--Lisp error: (wrong-type-argument listp "URL/HTTP Error: 200")
  assoc("categoryName" (nil . "URL/HTTP Error: 200"))
  #[(category) "\301\302\"A\207" [category assoc "categoryName"] 3]((nil . "URL/HTTP Error: 200"))
  mapcar(#[(category) "\301\302\"A\207" [category assoc "categoryName"] 3] ((nil . "URL/HTTP Error: 200")))
  org2blog/wp-login()
  org2blog/wp-new-entry()
  funcall-interactively(org2blog/wp-new-entry)
  #<subr call-interactively>(org2blog/wp-new-entry nil nil)
  ad-Advice-call-interactively(#<subr call-interactively> org2blog/wp-new-entry nil nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (org2blog/wp-new-entry nil nil))
  call-interactively(org2blog/wp-new-entry nil nil)
  command-execute(org2blog/wp-new-entry)

i updated all the packages including xml-rpc.el etc. org-mode 8.2.7c

**Comment by punchagan** [comment]
This looks similar to #177 and #182. Please change "http://username.wordpress.com/xmlrpc.php" to "https://username.wordpress.com/xmlrpc.php" (s/http/https)
