### ISSUE TITLE
Hanging on logging in

### ISSUE THREAD

**Issue by RenWenshan** [punchagan/org2blog#178]
Checked `http://wenshanren.org/xmlrpc.php` with http://xmlrpc.eritreo.it/ and it said the endpoint's working.

However, `M-x org2blog/wp-login`, then fill in the password (actually it doesn't matter what I enter here), the mini-buffer has "Contacting host: wenshanren.org:80" and Emacs hangs.

Any idea?

org2blog-pke.el:

```lisp
;;; -*- no-byte-compile: t -*-
(define-package "org2blog" "20150114.2301" "Blog from Org mode to wordpress" '((org "8.1") (xml-rpc "1.6.8") (metaweblog "0.1")))
```
```

**Comment by punchagan** [comment]
Did you update wordpress or something recently? Wordpress changed sites to use https for all sites they host. See #177

**Comment by RenWenshan** [comment]
@punchagan thanks, but changing the URL to `http://wenshanren.org/xmlrpc.php` does not work neither:

```
Opening TLS connection to `wenshanren.org'...
Opening TLS connection with `gnutls-cli --insecure -p 443 wenshanren.org'...failed
Opening TLS connection with `gnutls-cli --insecure -p 443 wenshanren.org --protocols ssl3'...failed
Opening TLS connection with `openssl s_client -connect wenshanren.org:443 -no_ssl2 -ign_eof'...done
```

I don't think this is going to work because I'm hosting WordPress myself and I don't actually have a SSL certificate.

**Comment by punchagan** [comment]
I wasn't expecting that to work, but I thought we would find some clues. I'll try to work on this, later today.

**Comment by punchagan** [comment]
I tried looking into it, for a bit, but couldn't figure out what the bug, was.  I'll take a look at it, later this week.

**Comment by RenWenshan** [comment]
Any update on this? I traced it down to the xml-rpc library, seems it couldn't establish the connection successfully here.

**Comment by RenWenshan** [comment]
it's working now, didn't do anything. There might was something wrong with my blog.
