### ISSUE TITLE
autoload org2blog/wp-post-buffer , org2blog/wp-post-buffer-and-publish  ?

### ISSUE THREAD

**Issue by xwl** [punchagan/org2blog#190]
Seems these two commands are the most useful.  How about making them autoload?

BTW, what is difference between org2blog/wp-post-buffer and org2blog/wp-post-buffer-as-page  ?

**Comment by grettke** [comment]
`org2blog/wp-post-buffer` takes your buffer contents and creates a [Post](https://codex.wordpress.org/Writing_Posts).  

`org2blog/wp-post-buffer-as-page` takes your buffer contents and creates a [Page](https://codex.wordpress.org/Pages). 

You can read all about the differences [here](https://en.support.wordpress.com/post-vs-page/).

**Comment by grettke** [comment]
Added and tested.
