### ISSUE TITLE
org2blog readme example has a single quote ' instead of backtick `

### ISSUE THREAD

**Issue by zenshinji** [punchagan/org2blog#191]
See https://github.com/punchagan/org2blog/issues/183

I received questions about the solution to my first issue #183. I directed them back to the github page. It's been pointed out that the first example under 'Usage' - 'Defining your blog setup' has a single quote and not a backtick.

Is there a difference between the two examples, that one and the later one including auth-source?

**Comment by RenWenshan** [comment]
the following link explains the difference

http://www.gnu.org/software/emacs/manual/html_node/elisp/Backquote.html

**Comment by punchagan** [comment]
Also, you can see that there is a second example that uses backticks.
