### ISSUE TITLE
format: Symbol’s function definition is void: org-export-solidify-link-text

### ISSUE THREAD

**Issue by grettke** [punchagan/org2blog#197]
**Environment**

Emacs Version: &ldquo;24.4.1&rdquo;

Org-Mode Version: &ldquo;8.3.1&rdquo;

Org2Blog/WP Version: &ldquo;0.5&rdquo;

Timestamp: &ldquo;Fri Sep 11 15:02:09 2015&rdquo;

Steps:

-   Run Emacs from Homebrew
-   Load Org-Mode from git
-   Load Org2Blog from git
-   Configure [the blog](https://github.com/grettke/help/blob/master/.emacs.el#L1882-#L1888)
-   Log in
-   Call `org2blog/wp-post-buffer`

Behavior

-   Expected
    -   Post posted
-   Actual
    -   Got error
        
        > format: Symbol&rsquo;s function definition is void: org-export-solidify-link-text

Research:

-   [ox-twbs](https://github.com/marsmining/ox-twbs/issues/7)
-   [ox-reveal](https://github.com/yjwen/org-reveal/issues/127)
-   Function [was removed](http://orgmode.org/w/?p=org-mode.git;a=commit;h=68eb1d0ab0c153a1403d3c80fb3049ddc57aa26c)

Solution:

-   [Use `org-export-get-reference` instead](http://orgmode.org/w/?p=org-mode.git;a=blobdiff;f=lisp/ox.el;h=d6dcc826290927f56e211328447c9e8d507797aa;hp=a6afc304af79444236905e12195fba0e13fdc831;hb=68eb1d0ab0c153a1403d3c80fb3049ddc57aa26c;hpb=459033265295723cbfb0fccb3577acbfdc9d0285).
    
    > Removed function `org-export-solidify-link-text`
    > This function, being non-bijective, introduced bug in internal
    > references.  Use `org-export-get-reference` instead.

Test:

-   Performed steps and article posted.

**Comment by punchagan** [comment]
Closed by #196
