### ISSUE TITLE
Marmalade File Download Not Up To Date

### ISSUE THREAD

**Issue by bradfonseca** [punchagan/org2blog#206]
Hello,

I recently successfully installed org2blog and love it so far. However, I ran into a hiccup during my install process that you may wish to be aware of.

In the README.org file, it states:

> Download org2blog from GitHub or Marmalade
> 
> git clone http://github.com/punchagan/org2blog.git
> 
> http://marmalade-repo.org/packages/org2blog

It seems as though the files located at the Marmalade site are not current. I eventually traced the problem to these files and fixed by downloading the files from GitHub.

Again, love being able to blog from Emacs with your software package!

Thanks,

Brad

**Comment by grettke** [comment]
Thank you for the pointer.

Now we only recommend pulling it from GitHub directly or using MELPA and use-package.
