### ISSUE TITLE
plist-get:Symbol's function definition is void: org-infile-export-plist

### ISSUE THREAD

**Issue by zhizunbao84** [punchagan/org2blog#208]
my computer's OS is win 8 
i use emacs 24.5 and org in it
after i install org2blog and set it up, i can login my wordpress blog.
but when i post existing org-file using "C-u M-x org2blog/wp-post-buffer", it tells:
   plist-get:Symbol's function definition is void: org-infile-export-plist

and when i use "C-c M-p p", it tells:
    C-c M-p is undefined

**Comment by zhizunbao84** [comment]
now I know how to solve it.
go to https://github.com/ptrv/org2blog and download the org2blog.el and replace the old one, then it is ok now.

**Comment by grettke** [comment]
Thank you @zhizunbao84 !

**Comment by punchagan** [comment]
Which version of org-mode are you on?
