### ISSUE TITLE
Unable to write "HTTP::Tiny" in blog text

### ISSUE THREAD

**Issue by oylenshpeegul** [punchagan/org2blog#218]
When I include the text HTTP::Tiny in a blog post, I get

    Wrong type argument: char-or-string-p, nil

when I try to post it. I created [this post](https://oylenshpeegul.wordpress.com/2016/07/06/metacpan-download-url) by writing

    HTTP&#x3a;&#x3a;Tiny

instead. Does something think HTTP: is the start of a URL or something? I looked in the *Messages* buffer and the message was

    get-file-properties: Wrong type argument: char-or-string-p, nil

I see that org2blog.el has a (get-file-properties file-name) in it, but I couldn't follow how we were getting to that branch in the code.

**Comment by punchagan** [comment]
It looks like something org-mode itself does.  

Try exporting a sample document with HTTP::Tiny as html, using org-mode. It doesn't work for me. If you can reproduce the error, please report a bug to org-mode. 

Alternatively, you can write the string as code using ~HTTP::Tiny~

**Comment by oylenshpeegul** [comment]
Great idea, thanks for the reply!

I created an org document that contained *only* the text 

    HTTP::Tiny

and exported it as HTML. It didn't give me the wrong type argument, but it created an HTML document containing the text

    :Tiny

That is, it silently ate the HTTP:. So I think you're right, there's something going on with org-mode itself...but that's not the whole story. And yes, the same experiment with the string ~HTTP::Tiny~ created an HTML page with the whole HTTP::Tiny (in fixed width font).

Thanks again!

**Comment by punchagan** [comment]
Thanks for the detailed reply.
