### ISSUE TITLE
Can't login even though using https

### ISSUE THREAD

**Issue by Cumol** [punchagan/org2blog#220]
Not able to login. It is my first try to use org2blog

`Debugger entered--Lisp error: (error "Error during request: 404")
  signal(error ("Error during request: 404"))
  error("Error during request: %s" 404)
  xml-rpc-request("https://lab.username.org//blog/wordpress/xmlrpc.php" ((methodCall nil (methodName nil "metaWeblog.getCategories") (params nil (param nil (value nil (string nil "1"))) (param nil (value nil (string nil "username"))) (param nil (value nil (string nil "mypassword")))))) nil)
  xml-rpc-method-call-async(nil "https://lab.username.org//blog/wordpress/xmlrpc.php" "metaWeblog.getCategories" ("1" "username" "mypassword"))
  xml-rpc-method-call("https://lab.username.org//blog/wordpress/xmlrpc.php" "metaWeblog.getCategories" "1" "username" "mypassword")
  metaweblog-get-categories("https://lab.username.org//blog/wordpress/xmlrpc.php" "username" "mypassword" "1")
  (mapcar (function (lambda (category) (cdr (assoc "categoryName" category)))) (metaweblog-get-categories org2blog/wp-server-xmlrpc-url org2blog/wp-server-userid org2blog/wp-server-pass org2blog/wp-server-blogid))
  (setq org2blog/wp-blog (assoc org2blog/wp-blog-name org2blog/wp-blog-alist) org2blog/wp-server-xmlrpc-url (plist-get (cdr org2blog/wp-blog) :url) org2blog/wp-server-userid (plist-get (cdr org2blog/wp-blog) :username) org2blog/wp-server-blogid (or (plist-get (cdr org2blog/wp-blog) :id) "1") org2blog/wp-server-pass (or (plist-get (cdr org2blog/wp-blog) :password) (read-passwd (format "%s Weblog password? " org2blog/wp-blog-name))) org2blog/wp-categories-list (mapcar (function (lambda (category) (cdr (assoc "categoryName" category)))) (metaweblog-get-categories org2blog/wp-server-xmlrpc-url org2blog/wp-server-userid org2blog/wp-server-pass org2blog/wp-server-blogid)) org2blog/wp-tags-list (mapcar (function (lambda (tag) (cdr (assoc "slug" tag)))) (wp-get-tags org2blog/wp-server-xmlrpc-url org2blog/wp-server-userid org2blog/wp-server-pass org2blog/wp-server-blogid)) org2blog/wp-pages-list (mapcar (function (lambda (pg) (cons (cdr (assoc "page_title" pg)) (cdr (assoc "page_id" pg))))) (wp-get-pagelist org2blog/wp-server-xmlrpc-url org2blog/wp-server-userid org2blog/wp-server-pass org2blog/wp-server-blogid)))
  (let nil (setq org2blog/wp-blog-name (or blog-name (and (equal (length org2blog/wp-blog-alist) 1) (car (car org2blog/wp-blog-alist))) (completing-read "Blog to login into? ([Tab] to see list): " (mapcar (quote car) org2blog/wp-blog-alist) nil t))) (if (> (length org2blog/wp-blog-name) 1) nil (error "Invalid blog name")) (setq org2blog/wp-blog (assoc org2blog/wp-blog-name org2blog/wp-blog-alist) org2blog/wp-server-xmlrpc-url (plist-get (cdr org2blog/wp-blog) :url) org2blog/wp-server-userid (plist-get (cdr org2blog/wp-blog) :username) org2blog/wp-server-blogid (or (plist-get (cdr org2blog/wp-blog) :id) "1") org2blog/wp-server-pass (or (plist-get (cdr org2blog/wp-blog) :password) (read-passwd (format "%s Weblog password? " org2blog/wp-blog-name))) org2blog/wp-categories-list (mapcar (function (lambda (category) (cdr (assoc "categoryName" category)))) (metaweblog-get-categories org2blog/wp-server-xmlrpc-url org2blog/wp-server-userid org2blog/wp-server-pass org2blog/wp-server-blogid)) org2blog/wp-tags-list (mapcar (function (lambda (tag) (cdr (assoc "slug" tag)))) (wp-get-tags org2blog/wp-server-xmlrpc-url org2blog/wp-server-userid org2blog/wp-server-pass org2blog/wp-server-blogid)) org2blog/wp-pages-list (mapcar (function (lambda (pg) (cons (cdr (assoc "page_title" pg)) (cdr (assoc "page_id" pg))))) (wp-get-pagelist org2blog/wp-server-xmlrpc-url org2blog/wp-server-userid org2blog/wp-server-pass org2blog/wp-server-blogid))) (setq org2blog/wp-logged-in t) (message "Logged in"))
  org2blog/wp-login()
  funcall-interactively(org2blog/wp-login)
  call-interactively(org2blog/wp-login record nil)
  command-execute(org2blog/wp-login record)
  helm-M-x(nil "org2blog/wp-login")
  funcall-interactively(helm-M-x nil "org2blog/wp-login")
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)
`

**Comment by treese** [comment]
The 404 error means that the URL was not found on the server, which suggests that XML RPC for remote posting is not enabled on your Wordpress site. Did you turn it on? I think it's under Settings -> Writing -> Remote Publishing or something like that.

**Comment by Cumol** [comment]
My URL was incorrect, the problem was solved!
