### ISSUE TITLE
importing and inserting content from a single WP post

### ISSUE THREAD

**Issue by edgimar** [punchagan/org2blog#221]
I sometimes don't have access to emacs and will begin drafting a WordPress post (on WordPress).  It would be convenient if there were a way to simply specify the post id in an org file and then call a function to import and *insert* the contents of the existing post into the current buffer.  I'm mainly looking for something to do the equivalent of my having to manually log into the WP site, find the draft, and copy and paste content.  It wouldn't need to be lossless with respect to preserving formatting, etc.

**Comment by edgimar** [comment]
It occurs to me now that it doesn't make sense to require the user to input the posts ID.  It would therefore be better to automatically take the last post or draft, and/or to offer a menu of the last N posts.

**Comment by grettke** [comment]
That sounds like a great user interface functionality that doesn't exist right now. I don't want to work on that right now. 

However, you can export from WordPress to XML and migrate that to Org-Mode files using [this](https://github.com/punchagan/org2blog-importers/blob/master/wp_to_org2blog.py). 

You can use that right now so I'm going to close this issue.
