### ISSUE TITLE
Why can not support Chinese in the .org file?

### ISSUE THREAD

**Issue by HaixiWu** [punchagan/org2blog#223]
I've set up the org2blog. Buf If I am using Chinese, then the .org file can't be post.

**Comment by grettke** [comment]
Wondering if the database encoding is happy: Are you able to manually make the post using the same title and same content?

Wondering what happens if you try posting it via XML RPC: Here are my notes on testing it but not dealing with posting which is what you see. However it might get you closer to an error message: https://github.com/punchagan/org2blog/issues/160

**Comment by HaixiWu** [comment]
I am using utf-8. The same title and content can be post until I add only a single Chinese word in it.

I use the suggested command M-x org2blog/wp-post-buffer or C-u M-x org2blog/wp-post-buffer, but not working well with Chinese inside.

**Comment by grettke** [comment]
What version of Emacs?

What version of Org Mode?

What version of Org2Blog?

What is a message that we can use to reproduce it?

What is the error message?

**Comment by HaixiWu** [comment]
Hi @grettke ,
I am using Emacs 25.1, org mode version 8.2.10, and the latest org2blog here. I set up org2blog according to the readme and did no further changes.

For example, I can post this .org file in UTF-8, by M-x org2blog/wp-post-buffer:
```
#+BLOG: myblog
#+POSTID: 207
#+DATE: [2017-01-08 Sun 19:37]
#+TITLE: Hello, World
#+TAGS: 
#+CATEGORY:

Hello!
```

However, if I add a Chinese word like this:
```
#+BLOG: myblog
#+POSTID: 207
#+DATE: [2017-01-08 Sun 19:37]
#+TITLE: Hello, World
#+TAGS: 
#+CATEGORY:


Hello!你好！
```
then I  can no longer post it.
A new buffer will show up with something like
```
……
     <value>
      <boolean>0</boolean>
      </value>
    </param>
  </params>
</methodCall>
```
The only difference between the above two cases is with or without Chinese inside, and if I delete the “你好！”(or other Chinese), everything works fine again...

Could you try to include a Chinese word: 中文 in your .org file and see if you can post it like usual? Thanks!

**Comment by gnohz** [comment]
Same here as @HaixiWu (and the same setup, emacs 25.1 and latest org)

I think the key error message is the following:

> error in process sentinel: url-http-create-request: Multibyte text in HTTP request: POST /xmlrpc.php HTTP/1.1

I also found this by google:

http://blog.somof.net/?p=1310

(and it also happened in python mode pointed out by other posts).

**Comment by HaixiWu** [comment]
@gnohz 
Thanks! 
I just simply copy and paste those code into my .emacs, then the problem solved! (though I don't understand how it works)
Now I can post with Chinese without any problems!

**Comment by grettke** [comment]
Thank you @gnohz and @HaixiWu .

Added a TODO [here](https://github.com/punchagan/org2blog/issues/225)

**Comment by grettke** [comment]
@gnohz  It has been a while but if you can please try out his patched xml-rpc.el for your use case.
[fix.zip](https://github.com/org2blog/org2blog/files/1099213/fix.zip)

**Comment by grettke** [comment]
This issue is resolved [here using this patch](https://github.com/org2blog/org2blog#unicode-character-support).
