### ISSUE TITLE
No post

### ISSUE THREAD

**Issue by PaulPichaureau** [punchagan/org2blog#224]
I try to install org2blog and org-mode for the very first time, and I'm unable to post any article on my wordpress blog.

My configuration is very basic:

```
(setq org2blog/wp-blog-alist
      '(("***"
         :url "https://***/xmlrpc.php"
         :username "paul"
         :default-title "--"
         :default-categories ("None")
         :tags-as-categories nil)
	))
```

when I try to publish the article, the category is created, but the buffer is not published. 

*Edit* Ok guys, after a lot of test, I've detected the source of the problem: buffers with accented characters are not posted. I don't know how to correct that... (And BTW I'm terribly sorry for the awfully generic title of issue :-( )

I am using Emacs 25.1, the latest version of org mode and org2blog on melpa and Wordpress 4.7

**Comment by HaixiWu** [comment]
I face the similar problem in #223: buffer with Chinese words can not be post... 
Also don't know how to fix it.

**Comment by grettke** [comment]
Thanks for posting this @PaulPichaureau 

The issue turned out to be a duplicated posted here

https://github.com/punchagan/org2blog/issues/225

So I'm closing this issue.

**Comment by grettke** [comment]
@PaulPichaureau @HaixiWu  It has been a while but if you can please try out his patched xml-rpc.el for your use case.
[fix.zip](https://github.com/org2blog/org2blog/files/1099213/fix.zip)
